### ISSUE TITLE
CatchUpSubscriptionSettings ResolveLinkTos configuration

### ISSUE THREAD

**Issue by pblachut** [riccardone/EventStore.Tools.Linker#17]
Currently it is not possible to configure `ResolveLinkTos` in  `CatchUpSubscriptionSettings `. It is always set to true.

In situation when projections are enabled on origin then the same event might be send to destination many times (one event saved in original stream and at least 2 events saved as linked events).

I think it will be good to add `ResolveLinkTos` property in `Settings` class and propagate the value to `CatchUpSubscriptionSettings`.

**Comment by riccardone** [comment]
Ok, thanks for pointing this out. Feel free to open a PR otherwise I will apply this change asap.

**Comment by riccardone** [comment]
Closed by https://github.com/riccardone/EventStore.Tools.Linker/pull/18
