### ISSUE TITLE
Possibility of many concurrent running subscriptions?

### ISSUE THREAD

**Issue by pblachut** [riccardone/EventStore.Tools.Linker#21]
In my opinion there might be possibility of race condition during stopping subscription and starting it again with optimized parameters. Added additional logging [here](https://github.com/pblachut/EventStore.Tools.Linker/commit/bfafdbec35ae954bd19fce5fc00292da248c8027) to prove it.

Subscription stop do not block the thread so in short period of time the same event might come in new and old subscription. Luckily it should not affect on replication beacuse wrong expected version will be thrown if the same event will be saved again.

I'm not sure what to do with this issue. Maybe it could stay as it is, I don't have valid solution for now. Additinal debug logs might be only added to source code, including [setting subsctiption name in catchup subscription settings](https://github.com/pblachut/EventStore.Tools.Linker/blob/bfafdbec35ae954bd19fce5fc00292da248c8027/src/Linker/LinkerService.cs#L277).

**Comment by riccardone** [comment]
The same event can come in new and old subscription not for the race condition but only as the position is saved asynchronously and then the new subscription normally pick up some already processed events. That is a normal behavior and it does not affect the replication. I'll have a look asap to your additional logs.

**Comment by pblachut** [comment]
Ok, you are right the events which I get in logs come from the position save delay. I totally agree that it should not affect replication because it is handled using wrong expected version. I also noticed that before starting new subscription, [current buffer is processed](https://github.com/riccardone/EventStore.Tools.Linker/blob/master/src/Linker/LinkerService.cs#L138) first, so it should take enough time to eliminate the risk (or decrease to minimum) of starting the new before successfuly stopping the old one.

I think this issue might be closed.
